// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnqgouwdzgryyyorgvte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZucWdvdXdkemdyeXl5b3JndnRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Mzc2MjAsImV4cCI6MjA3MTExMzYyMH0.-Id44Ccg2uWhdDx6FP4W_Qv-e5dbQDFAGox_wOcJwlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});